- name: ensure oskari user
  user: name=oskari shell=/bin/bash groups=admin append=yes

- name: ensure oskari's public key from github
  authorized_key: user=oskari key=https://github.com/OsQu.keys

- name: ensure wedding user
  user: name=wedding generate_ssh_key=yes ssh_key_file=.ssh/id_rsa
